/**
 * Port of py_gearworks.function_generators (the parts needed for bevel gears).
 */
import { ORIGIN, OUT, PI, RIGHT, Vec3 } from './defs.js';
import {
  fromEuler, mvmul, vadd, vcross, vdot, vnorm, vnormalize, vscale, vsub,
} from './vec.js';

export function rotateVectorZ(v: Vec3, angle: number): Vec3 {
  return mvmul(fromEuler('z', angle), v);
}

export function angleBetweenVectors(v1: Vec3, v2: Vec3): number {
  return Math.atan2(vnorm(vcross(v1, v2)), vdot(v1, v2));
}

export function angleBetweenVectorAndPlane(v: Vec3, planeNormal: Vec3): number {
  const vPlane = vsub(v, vscale(planeNormal, vdot(v, planeNormal)));
  if (vnorm(vPlane) === 0) return PI / 2;
  return angleBetweenVectors(vPlane, v);
}

export function angleOfVectorInXY(v: Vec3): number {
  return Math.atan2(v[1], v[0]);
}

export function interpolateLin(
  x: number, x0: number, x1: number, y0: number, y1: number,
): number {
  return y0 + ((y1 - y0) * (x - x0)) / (x1 - x0);
}

/**
 * Circle involute curve.
 * t: rolling angle, r: base circle radius, angle: start angle offset,
 * vOffs: offset vector rotating with the tangent (used for trochoids).
 */
export function involuteCircle(
  t: number, r = 1, angle = 0, vOffs: Vec3 = ORIGIN, zOffs = 0,
): Vec3 {
  const rotZ = fromEuler('z', t + angle);
  // r*RIGHT + r*t*DOWN + vOffs
  const p: Vec3 = [r + vOffs[0], -r * t + vOffs[1], vOffs[2]];
  const v = mvmul(rotZ, p);
  return [v[0], v[1], v[2] + zOffs];
}

/**
 * Spherical involute curve.
 * r: base circle radius, C: spherical curvature (1/R); C=0 falls back to circle involute.
 */
export function involuteSphere(
  t: number, r = 1, C = 0.5, angle = 0, vOffs: Vec3 = ORIGIN, zOffs = 0,
): Vec3 {
  if (C === 0) return involuteCircle(t, r, angle, vOffs, zOffs);
  const R = 1 / Math.abs(C);
  const csig = Math.sign(C);
  const phi = (r / R) * t;
  const v1 = vadd(mvmul(fromEuler('y', (-PI / 2) * csig), vOffs), vscale(RIGHT, R));
  const beta = Math.asin(r / R);
  const zCenter = vscale(OUT, Math.sqrt(R * R - r * r) * csig);
  const rotChain = fromEuler('zyz', [-phi, (PI / 2 - beta) * csig, t + angle]);
  const v2 = vadd(vadd(mvmul(rotChain, v1), zCenter), vscale(OUT, zOffs));
  return v2;
}

/**
 * Octoid (spherical involute generated by flat-flank crown rack) curve for bevel gears.
 * From Giorgio Figliolini: "Algorithms for Involute and Octoidal Bevel-Gear Generation",
 * DOI: 10.1115/1.1900147.
 */
export function octoidFn(
  t: number,
  baseRad = 0.5,
  sphereRad = 1.0,
  alpha = (20 * PI) / 180,
  angle = 0.0,
): Vec3 {
  const beta = Math.asin(baseRad / sphereRad);
  const alpha1 = t;
  const r = sphereRad;

  const s = Math.sin;
  const c = Math.cos;
  const s2 = (x: number) => Math.sin(x) ** 2;
  const c2 = (x: number) => Math.cos(x) ** 2;

  const a1sb = alpha1 * s(beta);

  const R = -r / Math.sqrt(s2(alpha) * s2(a1sb) + c2(a1sb));

  const v0 =
    -c2(alpha) * c(alpha1) * s(a1sb) * c(a1sb) +
    s(beta) * s2(alpha) * s(alpha1) * s2(a1sb) +
    c(beta) * s(alpha) * c(alpha) * s(alpha1) * s(a1sb) +
    s(beta) * s(alpha1) * c2(a1sb);

  const v1 =
    +c2(alpha) * s(alpha1) * s(a1sb) * c(a1sb) +
    s(beta) * s2(alpha) * c(alpha1) * s2(a1sb) +
    c(beta) * s(alpha) * c(alpha) * c(alpha1) * s(a1sb) +
    s(beta) * c(alpha1) * c2(a1sb);

  const v2 =
    -c(beta) * s2(alpha) * s2(a1sb) +
    s(beta) * s(alpha) * c(alpha) * s(a1sb) -
    c(beta) * c2(a1sb);

  const v: Vec3 = [v0 * R, v1 * R, v2 * R];

  const rot = fromEuler('yz', [PI, PI / 2 + angle]);
  const zshift = Math.sqrt(sphereRad * sphereRad - baseRad * baseRad);
  const vr = mvmul(rot, v);
  return [vr[0], vr[1], vr[2] + zshift];
}

/** Contact curve of the octoid generation (same reference as octoidFn). */
export function octoidContactFn(
  t: number,
  baseRad = 0.5,
  sphereRad = 1.0,
  alpha = (20 * PI) / 180,
  angle = 0.0,
): Vec3 {
  const beta = Math.asin(baseRad / sphereRad);
  const alpha1 = t;
  const r = sphereRad;

  const s = Math.sin;
  const c = Math.cos;
  const s2 = (x: number) => Math.sin(x) ** 2;
  const c2 = (x: number) => Math.cos(x) ** 2;

  const a1sb = alpha1 * s(beta);
  const R = -r / Math.sqrt(s2(alpha) * s2(a1sb) + c2(a1sb));

  const v0 = c2(alpha) * s(a1sb) * c(a1sb);
  const v1 = -s2(alpha) * s2(a1sb) - c2(a1sb);
  const v2 = s(alpha) * c(alpha) * s(a1sb);

  const v: Vec3 = [v0 * R, v1 * R, v2 * R];
  const rot = fromEuler('yz', [PI, -PI / 2 + angle]);
  const zshift = Math.sqrt(sphereRad * sphereRad - baseRad * baseRad);
  const vr = mvmul(rot, v);
  return [vr[0], vr[1], vr[2] + zshift];
}

/** Convert cartesian to spherical [r, phi(azimuth), theta(polar)] around a center. */
export function xyzToSpherical(v: Vec3, center: Vec3 = ORIGIN): Vec3 {
  const d = vsub(v, center);
  const r = vnorm(d);
  const theta = Math.acos(d[2] / r);
  const phi = Math.atan2(d[1], d[0]);
  return [r, phi, theta];
}

/** Convert spherical [r, phi, theta] to cartesian around a center. */
export function sphericalToXyz(s: Vec3, center: Vec3 = ORIGIN): Vec3 {
  const [r, phi, theta] = s;
  return [
    r * Math.sin(theta) * Math.cos(phi) + center[0],
    r * Math.sin(theta) * Math.sin(phi) + center[1],
    r * Math.cos(theta) + center[2],
  ];
}

export function xyzToCylindrical(v: Vec3, center: Vec3 = ORIGIN): Vec3 {
  const d = vsub(v, center);
  return [Math.hypot(d[0], d[1]), Math.atan2(d[1], d[0]), d[2]];
}

export function cylindricalToXyz(c: Vec3, center: Vec3 = ORIGIN): Vec3 {
  const [r, phi, z] = c;
  return [r * Math.cos(phi) + center[0], r * Math.sin(phi) + center[1], z + center[2]];
}

/**
 * Exact rational quadratic bezier representation of a circular arc (< 180 deg).
 * Returns [points, weights].
 */
export function calcNurbezierArc(
  p0: Vec3, p2: Vec3, center: Vec3,
): { points: [Vec3, Vec3, Vec3]; weights: [number, number, number] } {
  const pmid = vscale(vadd(p0, p2), 0.5);
  const hAngle = angleBetweenVectors(vsub(p0, center), vsub(p2, center)) / 2;
  const radius = (vnorm(vsub(p0, center)) + vnorm(vsub(p2, center))) / 2;
  const dir = vnormalize(vsub(pmid, center));
  const p1 = vadd(
    vscale(dir, (Math.sin(hAngle) ** 2 / Math.cos(hAngle) + Math.cos(hAngle)) * radius),
    center,
  );
  return { points: [p0, p1, p2], weights: [1, Math.cos(hAngle), 1] };
}
